; 3.11

;each call to 'make-account' creates a frame containing the state of 'balance'. Each dispatch call contains the 'amount' and uses the parent environment for 'balance'. 

;between 'acc' and 'acc2' only the body of the proceedures is shared, the state is stored in the different frames generated by each call of 'make-account'.
